# Generated by Django 5.2.7 on 2025-10-11 23:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillExtractionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(verbose_name='Job Description')),
                ('processing_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Completed'), (3, 'Failed')], default=0, verbose_name='Processing Status')),
                ('processing_done_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Processing Done At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('extracted_skills', models.ManyToManyField(blank=True, related_name='extraction_infos', to='job.skill', verbose_name='Extracted Skills')),
            ],
            options={
                'verbose_name': 'Skill Extraction Info',
                'verbose_name_plural': 'Skill Extraction Infos',
                'ordering': ['-id'],
            },
        ),
    ]
